In [1]:
pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 171.5/171.5 kB 2.0 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-many

In [2]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [3]:
pip install  chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.8/526.8 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 12.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.9/91.9 kB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 23.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.1/106.1 kB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 7.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 698.9/698.9 kB 28.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 3

In [4]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import chromadb

In [5]:
merged_df = pd.read_csv("/content/drive/MyDrive/Search_Engine/merged_df.csv")

In [8]:
merged_df.shape

(2887, 3)

In [10]:
df = merged_df.sample(n=2500)

In [11]:
df

num                                               name  \
367   9198980.0  becoming.elizabeth.s01.e08.to.death.we.must.st...   
1400  9187002.0  rubeusutori.in.habeodeu.s01.e01.love.story.at....   
452   9195799.0  the.virginian.s01.e14.the.man.from.the.sea.(19...   
2432  9190443.0  medium.s03.e07.mothers.little.helper.(2007).en...   
2043  9191628.0  steven.universe.s02.e01.full.disclosure.(2015)...   
...         ...                                                ...   
961   9199611.0    love.island.s04.e18.episode.4.18.(2022).eng.1cd   
2871  9186150.0  the.jeffersons.s05.e01.louises.painting.(1978)...   
1772  9183161.0                            defilada.(1989).eng.1cd   
813   9189404.0  dr.slump.s01.e38.arale.to.furareta.obocchaman....   
1164  9185018.0     teen.wolf.s05.e03.dreamcatchers.(2015).eng.1cd   

                                    file_content_chunks  
367   dialogue dialogue unknown po oh six hour huh d...  
1400  young man dialogue dialogue unknown po want bu...  
452   better thing sit mr hawke walking away one con...  
2432  ffff cool font font color ffff going say font ...  
2043  morning right goodbye mm mari tomorrow morning...  
...                                                 ...  
961   amanda oversight think alex gonna take zetrov ...  
2871  po dialogue dialogue unknown po cut dialogue d...  
1772  end bargain ok give back weapon sure yeah gonn...  
813   queen rise poisoning emperor china hundred sol...  
1164  want sleep weekend mom going town scrapbooking...  

[2500 rows x 3 columns]

In [12]:
df.info

<bound method DataFrame.info of             num                                               name  \
367   9198980.0  becoming.elizabeth.s01.e08.to.death.we.must.st...   
1400  9187002.0  rubeusutori.in.habeodeu.s01.e01.love.story.at....   
452   9195799.0  the.virginian.s01.e14.the.man.from.the.sea.(19...   
2432  9190443.0  medium.s03.e07.mothers.little.helper.(2007).en...   
2043  9191628.0  steven.universe.s02.e01.full.disclosure.(2015)...   
...         ...                                                ...   
961   9199611.0    love.island.s04.e18.episode.4.18.(2022).eng.1cd   
2871  9186150.0  the.jeffersons.s05.e01.louises.painting.(1978)...   
1772  9183161.0                            defilada.(1989).eng.1cd   
813   9189404.0  dr.slump.s01.e38.arale.to.furareta.obocchaman....   
1164  9185018.0     teen.wolf.s05.e03.dreamcatchers.(2015).eng.1cd   

                                    file_content_chunks  
367   dialogue dialogue unknown po oh six hour huh d...  
1400  young man dialogue dialogue unknown po want bu...  
452   better thing sit mr hawke walking away one con...  
2432  ffff cool font font color ffff going say font ...  
2043  morning right goodbye mm mari tomorrow morning...  
...                                                 ...  
961   amanda oversight think alex gonna take zetrov ...  
2871  po dialogue dialogue unknown po cut dialogue d...  
1772  end bargain ok give back weapon sure yeah gonn...  
813   queen rise poisoning emperor china hundred sol...  
1164  want sleep weekend mom going town scrapbooking...  

[2500 rows x 3 columns]>

In [13]:
from tqdm import tqdm, tqdm_notebook

In [14]:
tqdm.pandas()

In [15]:
df['doc_vector_pretrained_bert'] = df.file_content_chunks.progress_apply(model.encode)

df.head()

100%|██████████| 2500/2500 [05:50<00:00,  7.14it/s]


num                                               name  \
367   9198980.0  becoming.elizabeth.s01.e08.to.death.we.must.st...   
1400  9187002.0  rubeusutori.in.habeodeu.s01.e01.love.story.at....   
452   9195799.0  the.virginian.s01.e14.the.man.from.the.sea.(19...   
2432  9190443.0  medium.s03.e07.mothers.little.helper.(2007).en...   
2043  9191628.0  steven.universe.s02.e01.full.disclosure.(2015)...   

                                    file_content_chunks  \
367   dialogue dialogue unknown po oh six hour huh d...   
1400  young man dialogue dialogue unknown po want bu...   
452   better thing sit mr hawke walking away one con...   
2432  ffff cool font font color ffff going say font ...   
2043  morning right goodbye mm mari tomorrow morning...   

                             doc_vector_pretrained_bert  
367   [0.026627993, -0.0071558678, 0.036925614, -0.0...  
1400  [0.053864475, 0.0040625264, 0.011397366, -0.02...  
452   [-0.029510578, -0.035975434, -0.033329982, 0.0...  
2432  [-0.006233081, -0.062201355, 0.057721954, 0.00...  
2043  [-0.03280923, 0.0027826447, 0.063185066, 0.077...

In [16]:
merged_df

num                                               name  \
0     9192252.0  the.killer.a.girl.who.deserves.to.die.(2022).e...   
1     9192252.0  the.killer.a.girl.who.deserves.to.die.(2022).e...   
2     9192252.0  the.killer.a.girl.who.deserves.to.die.(2022).e...   
3     9192252.0  the.killer.a.girl.who.deserves.to.die.(2022).e...   
4     9192252.0  the.killer.a.girl.who.deserves.to.die.(2022).e...   
...         ...                                                ...   
2882  9183522.0  survivor.s15.e04.ride.the.workhorse.till.the.t...   
2883  9183522.0  survivor.s15.e04.ride.the.workhorse.till.the.t...   
2884  9183522.0  survivor.s15.e04.ride.the.workhorse.till.the.t...   
2885  9183522.0  survivor.s15.e04.ride.the.workhorse.till.the.t...   
2886  9183522.0  survivor.s15.e04.ride.the.workhorse.till.the.t...   

                                    file_content_chunks  
0     script info title english u original script tv...  
1     h b h style sign episode arial h fffadb h ff h...  
2     dialogue main gu last word activate dialogue m...  
3     main gu seen heart dialogue main gu ready dial...  
4     n battle though dialogue main gu goal get card...  
...                                                 ...  
2882  row right behind home zone tonight game two se...  
2883  jack speech honestly calling buck manzell hurt...  
2884  remember grandma earlier begged get cooky oven...  
2885  guy unnervingly tall two time wife got scraggl...  
2886  would believe rocket plush seat cocktail waitr...  

[2887 rows x 3 columns]

In [17]:
df

num                                               name  \
367   9198980.0  becoming.elizabeth.s01.e08.to.death.we.must.st...   
1400  9187002.0  rubeusutori.in.habeodeu.s01.e01.love.story.at....   
452   9195799.0  the.virginian.s01.e14.the.man.from.the.sea.(19...   
2432  9190443.0  medium.s03.e07.mothers.little.helper.(2007).en...   
2043  9191628.0  steven.universe.s02.e01.full.disclosure.(2015)...   
...         ...                                                ...   
961   9199611.0    love.island.s04.e18.episode.4.18.(2022).eng.1cd   
2871  9186150.0  the.jeffersons.s05.e01.louises.painting.(1978)...   
1772  9183161.0                            defilada.(1989).eng.1cd   
813   9189404.0  dr.slump.s01.e38.arale.to.furareta.obocchaman....   
1164  9185018.0     teen.wolf.s05.e03.dreamcatchers.(2015).eng.1cd   

                                    file_content_chunks  \
367   dialogue dialogue unknown po oh six hour huh d...   
1400  young man dialogue dialogue unknown po want bu...   
452   better thing sit mr hawke walking away one con...   
2432  ffff cool font font color ffff going say font ...   
2043  morning right goodbye mm mari tomorrow morning...   
...                                                 ...   
961   amanda oversight think alex gonna take zetrov ...   
2871  po dialogue dialogue unknown po cut dialogue d...   
1772  end bargain ok give back weapon sure yeah gonn...   
813   queen rise poisoning emperor china hundred sol...   
1164  want sleep weekend mom going town scrapbooking...   

                             doc_vector_pretrained_bert  
367   [0.026627993, -0.0071558678, 0.036925614, -0.0...  
1400  [0.053864475, 0.0040625264, 0.011397366, -0.02...  
452   [-0.029510578, -0.035975434, -0.033329982, 0.0...  
2432  [-0.006233081, -0.062201355, 0.057721954, 0.00...  
2043  [-0.03280923, 0.0027826447, 0.063185066, 0.077...  
...                                                 ...  
961   [-0.027465548, -0.058834232, -0.07316193, 0.00...  
2871  [0.008925586, -0.07501614, 0.04233364, -0.0506...  
1772  [-0.020518217, -0.054627467, -0.01782677, -0.0...  
813   [-0.04005998, -0.0380384, 0.006302292, 0.01884...  
1164  [-0.019497478, -0.07809276, 0.060564447, -0.00...  

[2500 rows x 4 columns]

In [18]:
User_query = pd.Series([input("Enter a user Query " )])

Enter a user Query Query peter


In [21]:
from tqdm import tqdm
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import pandas as pd

# Download NLTK resources if not already downloaded
import nltk
nltk.download('punkt')
nltk.download('wordnet')

# Define the preprocess function
def preprocess(text, method='lemma'):
    tokens = word_tokenize(text.lower())  # Tokenize and lowercase
    if method == 'lemma':
        lemmatizer = WordNetLemmatizer()
        tokens = [lemmatizer.lemmatize(token) for token in tokens]
    # Other preprocessing steps can be added here
    return ' '.join(tokens)  # Join tokens back into a string


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [22]:
User_query.progress_apply(lambda x:  preprocess(x, "lemma"))

100%|██████████| 1/1 [00:01<00:00,  1.63s/it]


0    query peter
dtype: object

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2500 entries, 367 to 1164
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   num                         2500 non-null   float64
 1   name                        2500 non-null   object 
 2   file_content_chunks         2500 non-null   object 
 3   doc_vector_pretrained_bert  2500 non-null   object 
dtypes: float64(1), object(3)
memory usage: 97.7+ KB


In [24]:
df['doc_vector_pretrained_bert'] = df['doc_vector_pretrained_bert'].astype(str).str.replace("[","").str.replace("]","")


In [25]:
df['doc_vector_pretrained_bert'] = df['doc_vector_pretrained_bert'].apply(lambda x: [float(i) for i in x.split()])


In [26]:
a=df['doc_vector_pretrained_bert'][:1]

In [27]:
len(a.loc[367,])

384

In [28]:
Query = User_query.progress_apply(model.encode)

100%|██████████| 1/1 [00:00<00:00, 29.01it/s]


In [29]:
Query[0].shape

(384,)

In [30]:
import torch

In [31]:
# Convert the DataFrame column into a list of tensors
doc_vectors = [torch.tensor(vec) for vec in df['doc_vector_pretrained_bert']]

# Assuming Query[0] is also a tensor, convert it if necessary
query_tensor = torch.tensor(Query[0])

# Calculate cosine similarity
cos_similarities = [util.cos_sim(query_tensor, vec) for vec in doc_vectors]

In [32]:
cos_similarities

[tensor([[0.2356]]),
 tensor([[0.1914]]),
 tensor([[0.1333]]),
 tensor([[0.1272]]),
 tensor([[0.1120]]),
 tensor([[-0.0278]]),
 tensor([[0.2159]]),
 tensor([[0.0641]]),
 tensor([[0.0832]]),
 tensor([[0.1443]]),
 tensor([[0.1364]]),
 tensor([[0.2185]]),
 tensor([[-0.0364]]),
 tensor([[0.0909]]),
 tensor([[0.0414]]),
 tensor([[0.0539]]),
 tensor([[0.2026]]),
 tensor([[0.0808]]),
 tensor([[0.1470]]),
 tensor([[0.1603]]),
 tensor([[0.0919]]),
 tensor([[0.0980]]),
 tensor([[0.0607]]),
 tensor([[0.0198]]),
 tensor([[0.1096]]),
 tensor([[0.0970]]),
 tensor([[0.0879]]),
 tensor([[0.1140]]),
 tensor([[0.1199]]),
 tensor([[0.0080]]),
 tensor([[0.2008]]),
 tensor([[0.0878]]),
 tensor([[-0.0240]]),
 tensor([[0.0934]]),
 tensor([[0.0245]]),
 tensor([[0.0223]]),
 tensor([[0.0849]]),
 tensor([[0.0565]]),
 tensor([[0.0239]]),
 tensor([[0.0600]]),
 tensor([[0.2134]]),
 tensor([[0.1135]]),
 tensor([[0.0645]]),
 tensor([[0.1699]]),
 tensor([[0.0841]]),
 tensor([[0.1338]]),
 tensor([[0.0856]]),
 tensor([[

In [33]:
import numpy as np

cos_similarities_array = np.array(cos_similarities)
sorted_indices = cos_similarities_array.argsort()[::-1].tolist()


In [34]:
sorted_indices

[[[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],
 [[0]],


In [37]:
# Assuming sorted_indices is a 3-dimensional list
flattened_indices = [item for sublist1 in sorted_indices for sublist2 in sublist1 for item in sublist2]


In [38]:
import numpy as np

# Assuming sorted_indices is a 3-dimensional list
flattened_indices = np.array(sorted_indices).flatten()


In [39]:
top_sub = merged_df.iloc[flattened_indices]


In [35]:
top_sub = merged_df.iloc[sorted_indices[::]]

ValueError: Buffer has wrong number of dimensions (expected 1, got 3)

In [40]:
a=top_sub['file_content_chunks']

In [41]:
a[0]

0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
                           ...                        
0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
0    script info title english u original script tv...
Name: file_content_chunks, Length: 2500, dtype: object

In [43]:
df.index

Index([ 367, 1400,  452, 2432, 2043,  179,  345, 2760, 2570, 2694,
       ...
       1504, 2333, 1292, 2532, 2475,  961, 2871, 1772,  813, 1164],
      dtype='int64', length=2500)

In [48]:
cos_sim = util.cos_sim(Query[:], df['doc_vector_pretrained_bert'])


/usr/local/lib/python3.10/dist-packages/sentence_transformers/util.py:38: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:275.)
  a = torch.tensor(a)


KeyError: 2

In [49]:
merged_df.to_csv("/content/drive/MyDrive/Search_Engine/Sub_Titles_with_32.csv",index=False)

In [50]:
df.to_csv("/content/drive/MyDrive/Search_Engine/Sub_Titles_BERT.csv",index=False)

In [51]:
doc_vectors[0]

tensor([ 2.6628e-02, -7.1559e-03,  3.6926e-02, -1.4055e-02, -1.2608e-01,
         5.2833e-02,  4.3964e-02, -4.1901e-02, -5.5353e-03, -1.7637e-02,
        -2.9411e-02, -2.7647e-02, -1.9528e-02, -3.8825e-02, -4.5387e-03,
        -4.2235e-02,  1.9991e-02, -4.0086e-02, -5.2635e-02,  6.3657e-02,
         6.5505e-02,  5.2065e-02, -2.2980e-02, -2.9242e-02, -8.5292e-02,
         3.4885e-02, -1.8581e-03, -5.4981e-02, -3.4424e-03, -6.6041e-02,
         2.1370e-02,  1.4696e-01,  3.8394e-02,  1.3415e-02, -3.4429e-05,
         4.3400e-02, -9.3436e-02,  8.3831e-02,  3.6422e-03,  4.9979e-02,
        -9.1860e-02, -3.3308e-02, -2.0202e-02, -8.2885e-02,  4.2660e-02,
        -6.9543e-02, -1.6499e-01, -7.1612e-02,  4.1368e-02, -5.7700e-02,
        -1.2556e-01, -9.9588e-03, -2.0549e-02, -9.5407e-03, -3.3726e-02,
        -4.6788e-02, -1.3863e-02,  2.0617e-03, -5.9636e-03, -4.8630e-02,
        -4.4796e-02,  3.4513e-02, -7.7163e-03,  6.4838e-02,  4.5372e-02,
         5.6400e-02, -7.5618e-02,  4.4646e-02,  1.8

In [52]:
client = chromadb.PersistentClient(path="Search_engine")

In [53]:
client

In [54]:
 collection = client.create_collection(
        name="search",
        metadata={"hnsw:space": "cosine"} # l2 is the default
    )

In [56]:
collection.get(include=["documents"])

{'ids': ['chunks_0', 'chunks_1'],
 'embeddings': None,
 'metadatas': None,
 'documents': ['script info title english u original script tvtm http www crunchyroll com user tvtm original translation original editing original timing synch point script updated update detail scripttype v collision normal playresx playresy timer wrapstyle v style format name fontname fontsize primarycolour secondarycolour outlinecolour backcolour bold italic underline strikeout scalex scaley spacing angle borderstyle outline shadow alignment marginl marginr marginv encoding style main trebuchet m h ffffff h ff h h style main top trebuchet m h ffffff h ff h h style italic trebuchet m h ffffff h ff h h style italic top trebuchet m h ffffff h ff h h style flashback trebuchet m h ffffff h ff h b h b style flashback italic trebuchet m h ffffff h ff h h style flashback top trebuchet m h ffffff h ff h b h b style black sign arial h h ff h ffffff h style sign arial h ffffff h ff h h style next time arial h fffadb h f

In [57]:
emb

tensor([-2.9511e-02, -3.5975e-02, -3.3330e-02,  2.7601e-02, -2.9152e-02,
         4.7179e-02,  3.3235e-02, -1.0788e-01, -4.9171e-02,  2.1758e-03,
         4.0706e-02, -1.7822e-02,  4.0983e-02, -9.6360e-03,  3.0913e-02,
         3.9806e-03,  1.3966e-01,  4.3210e-02, -1.2416e-01,  1.8343e-02,
         1.4602e-02, -1.2270e-02, -1.2384e-03, -4.5996e-02, -5.0125e-02,
         3.2814e-02, -7.3480e-02, -3.2034e-02, -2.6206e-02, -1.1016e-02,
        -3.9646e-03,  4.4647e-02,  3.3876e-02, -1.8821e-02, -2.0875e-02,
        -2.8097e-03,  1.4734e-04,  1.2460e-01,  7.3879e-02,  9.3971e-03,
        -8.1707e-02, -3.6655e-02, -4.3887e-02, -3.7825e-02, -5.8309e-02,
         2.2195e-02,  3.2116e-02, -3.3007e-02, -6.2347e-02, -8.0523e-02,
        -5.8656e-02,  3.0111e-02,  6.8333e-03,  5.5711e-02, -3.8466e-02,
        -9.6039e-02, -1.1027e-02,  1.2594e-02, -9.4889e-03, -2.2295e-02,
        -4.9103e-02, -2.0707e-02,  4.3036e-02,  6.4770e-02, -3.5699e-02,
        -3.4410e-02, -1.1795e-01, -3.2458e-02,  1.3

In [58]:
a=doc_vectors

In [63]:
emb = [doc_vectors for i in range(len(doc_vectors))]


In [64]:
df = df.reset_index()

In [65]:
df

index        num                                               name  \
0       367  9198980.0  becoming.elizabeth.s01.e08.to.death.we.must.st...   
1      1400  9187002.0  rubeusutori.in.habeodeu.s01.e01.love.story.at....   
2       452  9195799.0  the.virginian.s01.e14.the.man.from.the.sea.(19...   
3      2432  9190443.0  medium.s03.e07.mothers.little.helper.(2007).en...   
4      2043  9191628.0  steven.universe.s02.e01.full.disclosure.(2015)...   
...     ...        ...                                                ...   
2495    961  9199611.0    love.island.s04.e18.episode.4.18.(2022).eng.1cd   
2496   2871  9186150.0  the.jeffersons.s05.e01.louises.painting.(1978)...   
2497   1772  9183161.0                            defilada.(1989).eng.1cd   
2498    813  9189404.0  dr.slump.s01.e38.arale.to.furareta.obocchaman....   
2499   1164  9185018.0     teen.wolf.s05.e03.dreamcatchers.(2015).eng.1cd   

                                    file_content_chunks  \
0     dialogue dialogue unknown po oh six hour huh d...   
1     young man dialogue dialogue unknown po want bu...   
2     better thing sit mr hawke walking away one con...   
3     ffff cool font font color ffff going say font ...   
4     morning right goodbye mm mari tomorrow morning...   
...                                                 ...   
2495  amanda oversight think alex gonna take zetrov ...   
2496  po dialogue dialogue unknown po cut dialogue d...   
2497  end bargain ok give back weapon sure yeah gonn...   
2498  queen rise poisoning emperor china hundred sol...   
2499  want sleep weekend mom going town scrapbooking...   

                             doc_vector_pretrained_bert  
0     [0.0266279932, -0.00715586776, 0.0369256139, -...  
1     [0.0538644753, 0.00406252639, 0.0113973664, -0...  
2     [-0.0295105781, -0.0359754339, -0.0333299823, ...  
3     [-0.00623308122, -0.0622013547, 0.0577219538, ...  
4     [-0.0328092314, 0.0027826447, 0.063185066, 0.0...  
...                                                 ...  
2495  [-0.0274655484, -0.0588342324, -0.0731619298, ...  
2496  [0.00892558601, -0.0750161409, 0.0423336402, -...  
2497  [-0.0205182172, -0.0546274669, -0.0178267695, ...  
2498  [-0.04005998, -0.0380383991, 0.00630229199, 0....  
2499  [-0.0194974784, -0.0780927613, 0.0605644472, -...  

[2500 rows x 5 columns]